---
- name: Update apt cache
  apt: update_cache=true
  become: true
- name: Install packages from apt
  package:
    name:
      - git
      - vim
      - tmux
    state: present
  become: true
- name: Install ripgrep from .deb
  apt:
    deb: "{{ rg_deb_url }}"
  become: true
- name: Install fd debian package
  apt:
    deb: "{{ fd_deb_url }}"
  become: true
- name: Download fzf
  git:
    repo: https://github.com/junegunn/fzf
    depth: 1
    dest: ~/.fzf
- name: Install fzf
  command: ~/.fzf/install --all
- name: Clone .dotpliki repositorium
  git:
    repo: https://github.com/psacawa/.dotpliki
    dest: "~/.dotpliki"
    bare: true
- name: Install z
  git:
    repo: https://github.com/rupa/z
    dest: ~/.local/share/z

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: Checkout .dotpliki repositorium
  shell: git --git-dir=$HOME/.dotpliki --work-tree=$HOME checkout -f
  register: dotpliki_checkout_result
